sentences = [
    "truth was out there I saw it",
    "truth was out there YOU saw it",
    "truth was out there SHE saw it",
    "truth was out there WE saw it",
    "but nobody said a word",
    "Nobody said a fucking word",
    "So I asked",
    "What is this all about",
    "So I asked",
    "What is this all about",
    "So I asked ",
    "What is this all about",
    "And I kept asking",
    "Because I couldn’t get it",
    "What are we watching",
    "What is this all fucking about",
    "truth was out there I saw it",
    "truth was out there YOU saw it",
    "truth was out there SHE saw it",
    "truth was out there WE saw it",
    "But nobody said a word",
    "Nobody said a fucking word",
    "Nobody said a fucking word",
    "Nobody",
    "Nobody said a fucking word",
    "Nobody",
    "We were silent",
    "What are we watching",
]